from datetime import date, datetime

from .models import OpportunityStatus, VolunteerOpportunity, VolunteerPortal


def sample_opportunities() -> list[VolunteerOpportunity]:
    now = datetime.now()
    return [
        VolunteerOpportunity(
            id="sample-001",
            portal=VolunteerPortal.SAMPLE,
            title="Nonprofit homepage renewal planning support",
            organization="Seoul Community Welfare Center",
            location="Seoul",
            activity_area="IT / Planning",
            target_group="Nonprofit staff",
            required_skills=["Web planning", "UX writing", "Notion"],
            recognized_hours=4,
            recruitment_start_date=date(2026, 5, 1),
            recruitment_end_date=date(2026, 5, 31),
            activity_start_date=date(2026, 6, 3),
            activity_end_date=date(2026, 6, 3),
            volunteer_count=3,
            status=OpportunityStatus.OPEN,
            apply_url="https://www.1365.go.kr/",
            source_updated_at=now,
            summary="Help a welfare center reorganize pages and improve content structure.",
        ),
        VolunteerOpportunity(
            id="sample-002",
            portal=VolunteerPortal.SAMPLE,
            title="Career mentoring for young job seekers",
            organization="Gyeonggi Youth Foundation",
            location="Gyeonggi",
            activity_area="Mentoring",
            target_group="Youth",
            required_skills=["Career coaching", "Resume review", "Interview coaching"],
            recognized_hours=2,
            recruitment_start_date=date(2026, 5, 5),
            recruitment_end_date=date(2026, 6, 10),
            activity_start_date=date(2026, 6, 15),
            activity_end_date=date(2026, 6, 15),
            volunteer_count=10,
            status=OpportunityStatus.OPEN,
            apply_url="https://www.vms.or.kr/",
            source_updated_at=now,
            summary="Provide one-on-one mentoring using professional hiring experience.",
        ),
        VolunteerOpportunity(
            id="sample-003",
            portal=VolunteerPortal.SAMPLE,
            title="Data dashboard setup for volunteer center",
            organization="Incheon Volunteer Center",
            location="Incheon",
            activity_area="Data",
            target_group="Volunteer managers",
            required_skills=["Excel", "Data visualization", "Looker Studio"],
            recognized_hours=6,
            recruitment_start_date=date(2026, 5, 7),
            recruitment_end_date=date(2026, 5, 25),
            activity_start_date=date(2026, 6, 1),
            activity_end_date=date(2026, 6, 8),
            volunteer_count=2,
            status=OpportunityStatus.OPEN,
            apply_url="https://www.1365.go.kr/",
            source_updated_at=now,
            summary="Build a simple reporting dashboard for volunteer activity statistics.",
        ),
        VolunteerOpportunity(
            id="sample-004",
            portal=VolunteerPortal.SAMPLE,
            title="Small business branding consultation",
            organization="Local Social Economy Center",
            location="Busan",
            activity_area="Design / Marketing",
            target_group="Social enterprises",
            required_skills=["Brand strategy", "Graphic design", "Marketing"],
            recognized_hours=3,
            recruitment_start_date=date(2026, 5, 2),
            recruitment_end_date=date(2026, 6, 20),
            activity_start_date=date(2026, 6, 22),
            activity_end_date=date(2026, 6, 22),
            volunteer_count=5,
            status=OpportunityStatus.OPEN,
            apply_url="https://www.vms.or.kr/",
            source_updated_at=now,
            summary="Support social enterprises with brand message and visual direction.",
        ),
    ]